title: RiRi's Awesome Art
author: RiRi
email: RiRi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I like to paint and draw arts. 
  
  My best friend is my daddy. 
  
  I like to play with him.

# social links
twitter_username: DaddysRiRi


show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
